# -*- coding: utf-8 -*-
"""PaiNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQzumrmj6CVqAWyVfgCW-8iF60BMF6Ty

# PaiNN — QM9 Gap Prediction
Polarizable Atom Interaction Neural Network for predicting the HOMO-LUMO gap (Δε) on the QM9 dataset.

| Setting | Value |
|---|---|
| Hidden dim | 128 |
| Layers | 3 |
| Cutoff radius | 5.0 Å |
| Radial basis | 20 Gaussian RBFs |
| Optimizer | Adam, lr=5e-4, weight_decay=1e-8 |
| Scheduler | CosineAnnealingLR per epoch |
| Loss | L1 on MAD-normalised targets |
| Batch size | 96 |
| Split | 100k train / 18k val / ~13k test |
| Epochs | 50 |

## 1. Mount Google Drive
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd "/content/drive/MyDrive/Colab Notebooks/24-788/Project"
!pwd && ls

"""## 2. Install Dependencies"""

import torch

# Detect installed torch/cuda versions and install matching PyG wheels
TORCH = torch.__version__.split('+')[0]
CUDA  = 'cu' + torch.version.cuda.replace('.', '')
print(f"PyTorch: {torch.__version__}  |  CUDA: {torch.version.cuda}")

!pip install torch-scatter torch-sparse torch-cluster \
    -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html -q
!pip install torch-geometric wandb -q
print("Done.")

"""## 3. Imports"""

import os
import json
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import wandb
from torch import optim
from torch_geometric.datasets import QM9
from torch_geometric.loader import DataLoader
from torch_geometric.data import Batch
from torch_geometric.utils import scatter
from torch_geometric.nn import radius_graph
from IPython.display import clear_output

SAVE_DIR = "/content/drive/MyDrive/Colab Notebooks/24-788/Project/PaiNN"
os.makedirs(SAVE_DIR, exist_ok=True)
print("CUDA available:", torch.cuda.is_available())

"""## 4. Plot Utility"""

def plot_loss(epoch, train_history, val_history, best_val, best_ep):
    clear_output(wait=True)
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(range(1, epoch + 1), train_history, label='Train MAE')
    ax.plot(range(1, epoch + 1), val_history,   label='Val MAE', linestyle='--')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('MAE (meV)')
    ax.set_title(f'Gap MAE — PaiNN  |  Best Val: {best_val:.1f} meV (epoch {best_ep})')
    ax.legend()
    ax.grid(True)
    plt.tight_layout()
    plt.show()
    print('Recent epochs:')
    for i in range(max(0, epoch - 10), epoch):
        print(f'  Epoch {i+1:4d}  |  '
              f'Train: {train_history[i]:.1f} meV  '
              f'Val: {val_history[i]:.1f} meV')

"""## 5. Model Architecture
PaiNN maintains both scalar features `s` (invariant) and vector features `v` (equivariant)
per atom throughout the network. Messages mix scalar and vector channels, allowing
the model to encode directional geometric information without breaking equivariance.
"""

class GaussianRBF(nn.Module):
    """Gaussian radial basis functions for encoding interatomic distances."""
    def __init__(self, num_rbf=20, cutoff=5.0):
        super().__init__()
        centers = torch.linspace(0.0, cutoff, num_rbf)
        self.register_buffer('centers', centers)
        self.width = (cutoff / num_rbf) ** 2

    def forward(self, dist):
        # dist: [E] interatomic distances
        return torch.exp(-((dist.unsqueeze(-1) - self.centers) ** 2) / self.width)


class CosineCutoff(nn.Module):
    """Smooth cosine envelope to zero out interactions beyond cutoff."""
    def __init__(self, cutoff=5.0):
        super().__init__()
        self.cutoff = cutoff

    def forward(self, dist):
        return torch.where(
            dist < self.cutoff,
            0.5 * (torch.cos(dist * torch.pi / self.cutoff) + 1.0),
            torch.zeros_like(dist)
        )


class PaiNNMessage(nn.Module):
    """
    PaiNN message passing layer.
    Computes scalar and vector messages from neighboring atoms
    using RBF-encoded distances and unit direction vectors.
    """
    def __init__(self, hidden_dim, num_rbf=20, cutoff=5.0):
        super().__init__()
        self.rbf      = GaussianRBF(num_rbf, cutoff)
        self.cutoff   = CosineCutoff(cutoff)

        # Maps RBF-encoded distances to 3 * hidden_dim filter weights
        self.filter_net = nn.Sequential(
            nn.Linear(num_rbf, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, 3 * hidden_dim),
        )

        # Maps scalar features to 3 * hidden_dim before filtering
        self.scalar_net = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, 3 * hidden_dim),
        )

    def forward(self, s, v, edge_index, pos):
        """
        s: [N, hidden] scalar features
        v: [N, 3, hidden] vector features
        edge_index: [2, E] graph connectivity
        pos: [N, 3] atom positions
        """
        row, col = edge_index

        # Compute displacement vectors and distances
        diff = pos[row] - pos[col]                          # [E, 3]
        dist = diff.norm(dim=-1, keepdim=True).clamp(min=1e-8)  # [E, 1]
        unit = diff / dist                                   # [E, 3] unit vectors
        dist = dist.squeeze(-1)                              # [E]

        # RBF encoding with cutoff envelope
        rbf_out    = self.rbf(dist)                          # [E, num_rbf]
        envelope   = self.cutoff(dist).unsqueeze(-1)         # [E, 1]
        filter_out = self.filter_net(rbf_out) * envelope     # [E, 3*hidden]

        # Split filter into three components
        W1, W2, W3 = filter_out.chunk(3, dim=-1)             # each [E, hidden]

        # Transform source scalar features
        phi = self.scalar_net(s[col])                        # [E, 3*hidden]
        P1, P2, P3 = phi.chunk(3, dim=-1)

        # Scalar messages
        ds_msg = P1 * W1                                     # [E, hidden]

        # Vector messages: two contributions
        # (1) from existing vector features at source
        v_src   = v[col]                                     # [E, 3, hidden]
        v_msg1  = v_src * (P2 * W2).unsqueeze(1)            # [E, 3, hidden]
        # (2) from unit direction vectors
        v_msg2  = unit.unsqueeze(-1) * (P3 * W3).unsqueeze(1)  # [E, 3, hidden]
        dv_msg  = v_msg1 + v_msg2

        # Aggregate messages at target nodes
        ds = scatter(ds_msg, row, dim=0, dim_size=s.size(0), reduce='sum')  # [N, hidden]
        dv = scatter(dv_msg, row, dim=0, dim_size=s.size(0), reduce='sum')  # [N, 3, hidden]

        return s + ds, v + dv


class PaiNNUpdate(nn.Module):
    """
    PaiNN update layer.
    Mixes scalar and vector channels using inner products of vector features
    to produce equivariant updates.
    """
    def __init__(self, hidden_dim):
        super().__init__()
        self.U = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.V = nn.Linear(hidden_dim, hidden_dim, bias=False)

        # Maps [scalar, |Vv|] → 3 * hidden for update gates
        self.update_net = nn.Sequential(
            nn.Linear(2 * hidden_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, 3 * hidden_dim),
        )

    def forward(self, s, v):
        # Apply learnable linear maps to vector features
        Uv = torch.einsum('nch,hd->ncd', v, self.U.weight)  # [N, 3, hidden]
        Vv = torch.einsum('nch,hd->ncd', v, self.V.weight)  # [N, 3, hidden]

        # Scalar invariant from inner product of vector features
        vv_norm = (Vv * Vv).sum(dim=1)                       # [N, hidden]

        # Concatenate scalar features with vector norm for update network
        a = self.update_net(torch.cat([s, vv_norm], dim=-1)) # [N, 3*hidden]
        a1, a2, a3 = a.chunk(3, dim=-1)

        # Scalar update
        ds = a1 + a3 * (Uv * Vv).sum(dim=1)                 # [N, hidden]

        # Vector update
        dv = Uv * a2.unsqueeze(1)                            # [N, 3, hidden]

        return s + ds, v + dv


class PaiNNModel(nn.Module):
    """Full PaiNN model: embedding → N (message + update) layers → readout."""
    def __init__(self, hidden_dim=128, n_layers=3, num_rbf=20,
                 cutoff=5.0, max_neighbors=32):
        super().__init__()
        self.cutoff        = cutoff
        self.max_neighbors = max_neighbors

        # Atom type embedding: atomic numbers 1–9 (H to F in QM9)
        self.embedding = nn.Embedding(10, hidden_dim)

        self.message_layers = nn.ModuleList([
            PaiNNMessage(hidden_dim, num_rbf, cutoff) for _ in range(n_layers)
        ])
        self.update_layers  = nn.ModuleList([
            PaiNNUpdate(hidden_dim) for _ in range(n_layers)
        ])

        # Readout: scalar features → per-atom energy → sum pooling
        self.readout = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.SiLU(),
            nn.Linear(hidden_dim // 2, 1),
        )

    def forward(self, z, pos, batch):
        # Build radius graph edges within cutoff distance
        edge_index = radius_graph(
            pos, r=self.cutoff, batch=batch,
            max_num_neighbors=self.max_neighbors
        )

        # Initialise scalar features from atom embeddings, vectors at zero
        s = self.embedding(z)                                # [N, hidden]
        v = torch.zeros(s.size(0), 3, s.size(1),
                        device=s.device, dtype=s.dtype)      # [N, 3, hidden]

        # Alternating message and update passes
        for msg, upd in zip(self.message_layers, self.update_layers):
            s, v = msg(s, v, edge_index, pos)
            s, v = upd(s, v)

        # Per-atom readout then sum pooling over atoms
        atom_out = self.readout(s).squeeze(-1)               # [N]
        return scatter(atom_out, batch, dim=0, reduce='sum') # [B]

"""## 6. Dataset"""

DATA_ROOT = "/content/drive/MyDrive/Colab Notebooks/24-788/Project/data/QM9"
dataset   = QM9(root=DATA_ROOT)
print(f"Dataset: {len(dataset)} molecules")

TARGET_IDX = 4       # Gap (Δε) in eV
BATCH_SIZE = 96

# Split: 100k train / 18k val / ~13k test
train_dataset = dataset[:100000]
val_dataset   = dataset[100000:118000]
test_dataset  = dataset[118000:]
print(f"Train/Val/Test: {len(train_dataset)}/{len(val_dataset)}/{len(test_dataset)}")

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

"""## 7. Target Normalisation"""

EV_TO_MEV = 1000.0

# Compute mean and MAD on training targets only
train_targets = torch.stack([train_dataset[i].y[0, TARGET_IDX] for i in range(len(train_dataset))])
target_mean   = train_targets.mean().item()
target_mad    = (train_targets - train_targets.mean()).abs().mean().item()

def normalize(y):   return (y - target_mean) / target_mad
def denormalize(y): return y * target_mad + target_mean

print(f"Gap mean: {target_mean * EV_TO_MEV:.1f} meV  |  MAD: {target_mad * EV_TO_MEV:.1f} meV")

"""## 8. Model, Optimiser & Scheduler"""

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print("Device:", device)

torch.manual_seed(42)
torch.cuda.manual_seed(42)

model_config = {
    'hidden_dim':    128,
    'n_layers':      3,
    'num_rbf':       20,
    'cutoff':        5.0,
    'max_neighbors': 32,
}

model = PaiNNModel(**model_config).to(device)
print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

NUM_EPOCHS   = 50
lr           = 5e-4
optimizer    = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-8)
lr_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, NUM_EPOCHS)
criterion    = nn.L1Loss()
checkpoint   = os.path.join(SAVE_DIR, 'painn_best_model.pt')
config_file  = os.path.join(SAVE_DIR, 'painn_config.json')

"""## 9. Smoke Test"""

sample = Batch.from_data_list([train_dataset[0], train_dataset[1]]).to(device)
out    = model(sample.z, sample.pos, sample.batch)
print("Output shape:", out.shape)   # expected: [2]

"""## 10. W&B Initialisation"""

wandb.login()

wandb.init(
    project='painn-qm9',
    config={
        **model_config,
        'batch_size': BATCH_SIZE,
        'epochs':     NUM_EPOCHS,
        'lr':         lr,
        'target':     'gap',
        'normalisation': 'MAD',
    }
)

"""## 11. Training"""

PLOT_EVERY        = 10
SAVE_EVERY        = 10

train_mae_history = []
val_mae_history   = []
best_val_mae      = float('inf')
best_epoch        = 0

for epoch in range(1, NUM_EPOCHS + 1):

    # Training pass
    model.train()
    train_loss, train_count = 0.0, 0
    for batch in train_loader:
        batch      = batch.to(device)
        label      = batch.y[:, TARGET_IDX]
        label_norm = normalize(label)

        pred = model(batch.z, batch.pos, batch.batch)
        loss = criterion(pred, label_norm)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_loss  += loss.item() * batch.num_graphs
        train_count += batch.num_graphs

    lr_scheduler.step()
    # Convert normalised L1 loss back to meV
    train_mae = (train_loss / train_count) * target_mad * EV_TO_MEV

    # Validation pass
    model.eval()
    val_loss, val_count = 0.0, 0
    with torch.no_grad():
        for batch in val_loader:
            batch   = batch.to(device)
            preds   = denormalize(model(batch.z, batch.pos, batch.batch))
            val_loss  += (preds - batch.y[:, TARGET_IDX]).abs().sum().item()
            val_count += batch.num_graphs
    val_mae = (val_loss / val_count) * EV_TO_MEV

    train_mae_history.append(train_mae)
    val_mae_history.append(val_mae)

    current_lr = optimizer.param_groups[0]['lr']

    wandb.log({
        'train_mae_meV': train_mae,
        'val_mae_meV':   val_mae,
        'lr':            current_lr,
        'epoch':         epoch,
    })

    if val_mae < best_val_mae:
        best_val_mae = val_mae
        best_epoch   = epoch
        torch.save(model.state_dict(), checkpoint)
        print(f'  Best saved  (Val MAE: {best_val_mae:.1f} meV)')

    print(f'Epoch {epoch:03d}  |  '
          f'Train MAE: {train_mae:.2f} meV  '
          f'Val MAE: {val_mae:.2f} meV  '
          f'LR: {current_lr:.2e}')

    if epoch % PLOT_EVERY == 0:
        plot_loss(epoch, train_mae_history, val_mae_history, best_val_mae, best_epoch)

    if epoch % SAVE_EVERY == 0:
        torch.save({
            'model_state_dict':     model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'epoch':             epoch,
            'train_mae_history': train_mae_history,
            'val_mae_history':   val_mae_history,
            'best_val_mae':      best_val_mae,
            'best_epoch':        best_epoch,
        }, os.path.join(SAVE_DIR, 'painn_checkpoint.pt'))
        print(f'  Checkpoint saved at epoch {epoch}')

"""## 12. Test Evaluation"""

# Load best model weights for final evaluation
model.load_state_dict(torch.load(checkpoint, map_location=device))
model.eval()

test_loss, test_count = 0.0, 0
with torch.no_grad():
    for batch in test_loader:
        batch   = batch.to(device)
        preds   = denormalize(model(batch.z, batch.pos, batch.batch))
        test_loss  += (preds - batch.y[:, TARGET_IDX]).abs().sum().item()
        test_count += batch.num_graphs
test_mae = (test_loss / test_count) * EV_TO_MEV

print('=' * 40)
print(f'  Best Val MAE : {best_val_mae:.2f} meV  (epoch {best_epoch})')
print(f'  Test MAE     : {test_mae:.2f} meV')
print('=' * 40)

wandb.summary['best_val_mae_meV'] = best_val_mae
wandb.summary['test_mae_meV']     = test_mae
wandb.finish()

"""## 13. Save Config"""

with open(config_file, 'w') as f:
    json.dump({
        **model_config,
        'target_idx':       TARGET_IDX,
        'target_mean':      target_mean,
        'target_mad':       target_mad,
        'best_val_mae_meV': best_val_mae,
        'test_mae_meV':     test_mae,
    }, f, indent=2)

print('Config saved to:', config_file)
!ls "{SAVE_DIR}"

"""## 14. Resume Training"""

# LOAD_PATH = os.path.join(SAVE_DIR, 'painn_checkpoint.pt')
# ckpt = torch.load(LOAD_PATH, map_location=device)
# model.load_state_dict(ckpt['model_state_dict'])
# optimizer.load_state_dict(ckpt['optimizer_state_dict'])
# train_mae_history = ckpt['train_mae_history']
# val_mae_history   = ckpt['val_mae_history']
# best_val_mae      = ckpt['best_val_mae']
# best_epoch        = ckpt['best_epoch']
# start_epoch       = ckpt['epoch'] + 1
# for _ in range(start_epoch - 1):
#     lr_scheduler.step()
# print(f'Resumed from epoch {start_epoch - 1}  |  Best val: {best_val_mae:.1f} meV')
# # Update training loop to: for epoch in range(start_epoch, NUM_EPOCHS + 1):

