# -*- coding: utf-8 -*-
"""EGNN_wandb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RPrtfcn5wgRlYNcdi74qUocyVUgsV7o

# EGNN — QM9 Gap Prediction
E(n)-Equivariant Graph Neural Network for predicting the HOMO-LUMO gap (Δε) on the QM9 dataset.

| Setting | Value |
|---|---|
| Hidden dim | 128 |
| Layers | 7 |
| Node features | 15-dim |
| Attention | Enabled |
| Optimizer | Adam, lr=1e-3, weight_decay=1e-16 |
| Scheduler | CosineAnnealingLR per epoch |
| Loss | L1 on MAD-normalised targets |
| Batch size | 96 |
| Split | 100k train / 18k val / ~13k test |
| Epochs | 50 |

## 1. Mount Google Drive
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd "/content/drive/MyDrive/Colab Notebooks/24-788/Project"
!pwd && ls

"""## 2. Install Dependencies"""

import torch

# Detect installed torch/cuda versions and install matching PyG wheels
TORCH = torch.__version__.split('+')[0]
CUDA  = 'cu' + torch.version.cuda.replace('.', '')
print(f"PyTorch: {torch.__version__}  |  CUDA: {torch.version.cuda}")

!pip install torch-scatter torch-sparse torch-cluster \
    -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html -q
!pip install torch-geometric wandb -q
print("Done.")

"""## 3. Imports"""

import os
import json
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import wandb
from torch import optim
from torch_geometric.utils import scatter
from torch_geometric.datasets import QM9
from torch_geometric.loader import DataLoader
from torch_geometric.data import Batch
from IPython.display import clear_output

SAVE_DIR = "/content/drive/MyDrive/Colab Notebooks/24-788/Project/EGNN"
os.makedirs(SAVE_DIR, exist_ok=True)
print("CUDA available:", torch.cuda.is_available())

"""## 4. Plot Utility"""

def plot_loss(epoch, train_history, val_history, best_val, best_ep):
    clear_output(wait=True)
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(range(1, epoch + 1), train_history, label='Train MAE')
    ax.plot(range(1, epoch + 1), val_history,   label='Val MAE', linestyle='--')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('MAE (meV)')
    ax.set_title(f'Gap MAE — EGNN  |  Best Val: {best_val:.1f} meV (epoch {best_ep})')
    ax.legend()
    ax.grid(True)
    plt.tight_layout()
    plt.show()
    print('Recent epochs:')
    for i in range(max(0, epoch - 10), epoch):
        print(f'  Epoch {i+1:4d}  |  '
              f'Train: {train_history[i]:.1f} meV  '
              f'Val: {val_history[i]:.1f} meV')

"""## 5. Model Architecture"""

# Atom type mapping: atomic number → one-hot index (H C N O F)
ATOM_MAP     = {1: 0, 6: 1, 7: 2, 8: 3, 9: 4}
CHARGE_SCALE = 9.0   # normalisation factor (max atomic number in QM9)

def build_node_features(z):
    # 5-dim one-hot encoding of atom type
    idx     = torch.zeros_like(z)
    for atomic_num, one_hot_idx in ATOM_MAP.items():
        idx[z == atomic_num] = one_hot_idx
    one_hot = F.one_hot(idx, num_classes=5).float()          # [N, 5]

    # 3-dim charge features: (z/scale)^0, ^1, ^2
    charge_norm   = (z.float() / CHARGE_SCALE).unsqueeze(-1) # [N, 1]
    charge_tensor = torch.cat([
        torch.ones_like(charge_norm),
        charge_norm,
        charge_norm ** 2
    ], dim=-1)                                                # [N, 3]

    # Outer product of one-hot and charge features → 15-dim
    return (one_hot.unsqueeze(-1) * charge_tensor.unsqueeze(1)).view(z.shape[0], -1)


class EGNNLayer(nn.Module):
    """Single equivariant graph convolutional layer.
    Coordinates are not updated (invariant mode for static property prediction).
    """
    def __init__(self, hidden_nf):
        super().__init__()

        # Edge MLP: takes [h_i, h_j, squared_distance] as input
        self.edge_mlp = nn.Sequential(
            nn.Linear(hidden_nf * 2 + 1, hidden_nf),
            nn.SiLU(),
            nn.Linear(hidden_nf, hidden_nf),
            nn.SiLU(),
        )

        # Attention gate: scalar weight per edge message
        self.att_mlp = nn.Sequential(
            nn.Linear(hidden_nf, 1),
            nn.Sigmoid(),
        )

        # Node MLP: takes [h_i, aggregated_messages] as input, residual added
        self.node_mlp = nn.Sequential(
            nn.Linear(hidden_nf * 2, hidden_nf),
            nn.SiLU(),
            nn.Linear(hidden_nf, hidden_nf),
        )

    def forward(self, h, pos, edge_index):
        row, col = edge_index

        # Compute squared pairwise distances
        radial = ((pos[row] - pos[col]) ** 2).sum(dim=1, keepdim=True)  # [E, 1]

        # Edge update with attention
        edge_feat = self.edge_mlp(torch.cat([h[row], h[col], radial], dim=1))
        edge_feat = edge_feat * self.att_mlp(edge_feat)

        # Aggregate messages and update node features with residual
        aggr  = scatter(edge_feat, row, dim=0, dim_size=h.size(0), reduce='sum')
        h_new = self.node_mlp(torch.cat([h, aggr], dim=1))
        return h + h_new


class EGNNModel(nn.Module):
    """Full EGNN model: embedding → N layers → node MLP → sum pool → graph MLP."""
    def __init__(self, in_node_nf=15, hidden_nf=128, n_layers=7):
        super().__init__()
        self.embedding = nn.Linear(in_node_nf, hidden_nf)
        self.layers    = nn.ModuleList([EGNNLayer(hidden_nf) for _ in range(n_layers)])

        # Node-wise decoder applied before pooling
        self.node_dec  = nn.Sequential(
            nn.Linear(hidden_nf, hidden_nf), nn.SiLU(),
            nn.Linear(hidden_nf, hidden_nf),
        )

        # Graph-level decoder applied after sum pooling
        self.graph_dec = nn.Sequential(
            nn.Linear(hidden_nf, hidden_nf), nn.SiLU(),
            nn.Linear(hidden_nf, 1),
        )

    def forward(self, z, pos, edge_index, batch):
        h = self.embedding(build_node_features(z))
        for layer in self.layers:
            h = layer(h, pos, edge_index)
        h = self.node_dec(h)
        h = scatter(h, batch, dim=0, reduce='sum')
        return self.graph_dec(h).squeeze(-1)

"""## 6. Fully Connected Edge Builder"""

def make_fc_edge_index(batch):
    """Build fully connected edges (all atom pairs) within each molecule."""
    rows, cols = [], []
    for g in batch.unique():
        mask  = (batch == g).nonzero(as_tuple=True)[0]
        n     = mask.size(0)
        rows.append(mask.repeat_interleave(n))
        cols.append(mask.repeat(n))
    return torch.stack([torch.cat(rows), torch.cat(cols)])

"""## 7. Dataset"""

DATA_ROOT = "/content/drive/MyDrive/Colab Notebooks/24-788/Project/data/QM9"
dataset   = QM9(root=DATA_ROOT)
print(f"Dataset: {len(dataset)} molecules")

TARGET_IDX = 4       # Gap (Δε) in eV
BATCH_SIZE = 96

# Split: 100k train / 18k val / ~13k test
train_dataset = dataset[:100000]
val_dataset   = dataset[100000:118000]
test_dataset  = dataset[118000:]
print(f"Train/Val/Test: {len(train_dataset)}/{len(val_dataset)}/{len(test_dataset)}")

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

"""## 8. Target Normalisation"""

EV_TO_MEV = 1000.0

# Compute mean and MAD on training targets only
train_targets = torch.stack([train_dataset[i].y[0, TARGET_IDX] for i in range(len(train_dataset))])
target_mean   = train_targets.mean().item()
target_mad    = (train_targets - train_targets.mean()).abs().mean().item()

def normalize(y):
    return (y - target_mean) / target_mad

def denormalize(y_norm):
    return y_norm * target_mad + target_mean

print(f"Gap mean: {target_mean * EV_TO_MEV:.1f} meV  |  MAD: {target_mad * EV_TO_MEV:.1f} meV")

"""## 9. Model, Optimiser & Scheduler"""

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print("Device:", device)

torch.manual_seed(42)
torch.cuda.manual_seed(42)

model_config = {
    'in_node_nf': 15,
    'hidden_nf':  128,
    'n_layers':   7,
}

model = EGNNModel(**model_config).to(device)
print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

NUM_EPOCHS   = 50
lr           = 1e-3
optimizer    = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-16)
lr_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, NUM_EPOCHS)
criterion    = nn.L1Loss()
checkpoint   = os.path.join(SAVE_DIR, 'egnn_best_model.pt')
config_file  = os.path.join(SAVE_DIR, 'egnn_config.json')

"""## 10. W&B Initialisation"""

wandb.login()

wandb.init(
    project='egnn-qm9',
    config={
        **model_config,
        'batch_size': BATCH_SIZE,
        'epochs':     NUM_EPOCHS,
        'lr':         lr,
        'target':     'gap',
        'normalisation': 'MAD',
    }
)

"""## 11. Training"""

PLOT_EVERY        = 10
SAVE_EVERY        = 10

train_mae_history = []
val_mae_history   = []
best_val_mae      = float('inf')
best_epoch        = 0

for epoch in range(1, NUM_EPOCHS + 1):

    # Training pass
    model.train()
    train_loss, train_count = 0.0, 0
    for batch in train_loader:
        batch      = batch.to(device)
        fc_edges   = make_fc_edge_index(batch.batch).to(device)
        label      = batch.y[:, TARGET_IDX]
        label_norm = normalize(label)

        pred = model(batch.z, batch.pos, fc_edges, batch.batch)
        loss = criterion(pred, label_norm)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_loss  += loss.item() * batch.num_graphs
        train_count += batch.num_graphs

    lr_scheduler.step()
    # Train loss is in normalised space — convert to meV for reporting
    train_mae = (train_loss / train_count) * target_mad * EV_TO_MEV

    # Validation pass
    model.eval()
    val_loss, val_count = 0.0, 0
    with torch.no_grad():
        for batch in val_loader:
            batch    = batch.to(device)
            fc_edges = make_fc_edge_index(batch.batch).to(device)
            preds    = denormalize(model(batch.z, batch.pos, fc_edges, batch.batch))
            val_loss  += (preds - batch.y[:, TARGET_IDX]).abs().sum().item()
            val_count += batch.num_graphs
    val_mae = (val_loss / val_count) * EV_TO_MEV

    train_mae_history.append(train_mae)
    val_mae_history.append(val_mae)

    current_lr = optimizer.param_groups[0]['lr']

    # Log to W&B
    wandb.log({
        'train_mae_meV': train_mae,
        'val_mae_meV':   val_mae,
        'lr':            current_lr,
        'epoch':         epoch,
    })

    # Save best model
    if val_mae < best_val_mae:
        best_val_mae = val_mae
        best_epoch   = epoch
        torch.save(model.state_dict(), checkpoint)
        print(f'  Best saved  (Val MAE: {best_val_mae:.1f} meV)')

    print(f'Epoch {epoch:03d}  |  '
          f'Train MAE: {train_mae:.2f} meV  '
          f'Val MAE: {val_mae:.2f} meV  '
          f'LR: {current_lr:.2e}')

    if epoch % PLOT_EVERY == 0:
        plot_loss(epoch, train_mae_history, val_mae_history, best_val_mae, best_epoch)

    if epoch % SAVE_EVERY == 0:
        torch.save({
            'model_state_dict':     model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'epoch':             epoch,
            'train_mae_history': train_mae_history,
            'val_mae_history':   val_mae_history,
            'best_val_mae':      best_val_mae,
            'best_epoch':        best_epoch,
        }, os.path.join(SAVE_DIR, 'egnn_checkpoint.pt'))
        print(f'  Checkpoint saved at epoch {epoch}')

"""## 12. Test Evaluation"""

# Load best model weights for final evaluation
model.load_state_dict(torch.load(checkpoint, map_location=device))
model.eval()

test_loss, test_count = 0.0, 0
with torch.no_grad():
    for batch in test_loader:
        batch    = batch.to(device)
        fc_edges = make_fc_edge_index(batch.batch).to(device)
        preds    = denormalize(model(batch.z, batch.pos, fc_edges, batch.batch))
        test_loss  += (preds - batch.y[:, TARGET_IDX]).abs().sum().item()
        test_count += batch.num_graphs
test_mae = (test_loss / test_count) * EV_TO_MEV

print('=' * 40)
print(f'  Best Val MAE : {best_val_mae:.2f} meV  (epoch {best_epoch})')
print(f'  Test MAE     : {test_mae:.2f} meV')
print('=' * 40)

wandb.summary['best_val_mae_meV'] = best_val_mae
wandb.summary['test_mae_meV']     = test_mae
wandb.finish()

"""## 13. Save Config"""

# Save model config and results to JSON for reproducibility
with open(config_file, 'w') as f:
    json.dump({
        **model_config,
        'target_idx':        TARGET_IDX,
        'target_mean':       target_mean,
        'target_mad':        target_mad,
        'best_val_mae_meV':  best_val_mae,
        'test_mae_meV':      test_mae,
    }, f, indent=2)

print('Config saved to:', config_file)
!ls "{SAVE_DIR}"

"""## 14. Resume Training"""

# LOAD_PATH = os.path.join(SAVE_DIR, 'egnn_checkpoint.pt')
# ckpt = torch.load(LOAD_PATH, map_location=device)
# model.load_state_dict(ckpt['model_state_dict'])
# optimizer.load_state_dict(ckpt['optimizer_state_dict'])
# train_mae_history = ckpt['train_mae_history']
# val_mae_history   = ckpt['val_mae_history']
# best_val_mae      = ckpt['best_val_mae']
# best_epoch        = ckpt['best_epoch']
# start_epoch       = ckpt['epoch'] + 1
# for _ in range(start_epoch - 1):
#     lr_scheduler.step()
# print(f'Resumed from epoch {start_epoch - 1}  |  Best val: {best_val_mae:.1f} meV')
# # Update training loop to: for epoch in range(start_epoch, NUM_EPOCHS + 1):

!pip show torch torch-geometric torch-scatter torch-sparse torch-cluster numpy matplotlib wandb jupyter | grep -E "^(Name|Version)"

